### ISSUE TITLE
Support for profiles

### ISSUE THREAD

**Issue by jdrydn** [car-throttle/awsops#2]
Rather than specifying credentials in `awsops.yml` (o.e.) the AWS SDK falls back to the well-known `~/.aws/credentials` file. `awsops.yml` should therefore support setting the correct AWS profile [as discussed here](http://docs.aws.amazon.com/cli/latest/userguide/cli-chap-getting-started.html#cli-multiple-profiles). At the moment, my workaround is:

```
alias awesomedev="AWS_DEFAULT_PROFILE=car-throttle awsops --auth ~/.awsops.yml"

$ awesomedev ls --name awesome-server
```

It would be nicer to see:

```yaml
aws:
  profile: car-throttle
ssh:
  keys:
    blah: blah
```
